schema_version: 1

context:
  name: chemformula
  version: 1.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/chemformula-${{ version }}.tar.gz
  sha256: 0556362f90f6d6fe9d9316c04aaee0e0b7c132aab1fbc5249c9890839ec32c52

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - casregnum >=1.1.2

tests:
  - python:
      imports:
        - chemformula
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: ChemFormula is a Python class for working with chemical formulas. It allows parsing chemical formulas, generating formatted output strings and calculating formula weights.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/molshape/ChemFormula

extra:
  recipe-maintainers:
    - HLinde
